"""
FiveM resource scaffolder.

Generates a new resource folder with a complete fxmanifest.lua and starter
client/server/shared files for one of:
- 'basic' — plain FiveM resource
- 'esx'   — ESX-aware resource (registers an ESX command on init)
- 'qbcore'— QBCore-aware resource (registers a QBCore command)
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

TEMPLATES = ("basic", "esx", "qbcore")


@dataclass
class ScaffoldResult:
    path: str
    files: list[str]


def scaffold_resource(
    parent_dir: str,
    name: str,
    template: str = "basic",
    *,
    author: str = "",
    description: str = "",
    version: str = "1.0.0",
) -> ScaffoldResult:
    if template not in TEMPLATES:
        raise ValueError(f"Unknown template '{template}'. Use one of: {', '.join(TEMPLATES)}")
    safe = "".join(c for c in name if c.isalnum() or c in "_-").strip("_-")
    if not safe:
        raise ValueError("Resource name must contain alphanumeric/underscore/hyphen characters")
    root = Path(parent_dir) / safe
    if root.exists():
        raise FileExistsError(f"Resource folder already exists: {root}")

    root.mkdir(parents=True)
    files: list[str] = []

    manifest = _manifest_text(safe, template, author=author, description=description, version=version)
    (root / "fxmanifest.lua").write_text(manifest, encoding="utf-8")
    files.append("fxmanifest.lua")

    client = _client_text(safe, template)
    server = _server_text(safe, template)
    config = _config_text(safe)

    (root / "client.lua").write_text(client, encoding="utf-8")
    (root / "server.lua").write_text(server, encoding="utf-8")
    (root / "config.lua").write_text(config, encoding="utf-8")
    files.extend(["client.lua", "server.lua", "config.lua"])

    return ScaffoldResult(path=str(root), files=files)


def _manifest_text(name: str, template: str, *, author: str, description: str, version: str) -> str:
    desc = description or f"{template.title()} resource generated by Sanitize V"
    auth = author or "unknown"
    return (
        f"fx_version 'cerulean'\n"
        f"game 'gta5'\n"
        f"lua54 'yes'\n\n"
        f"name '{name}'\n"
        f"author '{auth}'\n"
        f"description '{desc}'\n"
        f"version '{version}'\n\n"
        f"shared_scripts {{\n"
        f"    'config.lua',\n"
        f"}}\n\n"
        f"client_scripts {{\n"
        f"    'client.lua',\n"
        f"}}\n\n"
        f"server_scripts {{\n"
        f"    'server.lua',\n"
        f"}}\n"
    )


def _client_text(name: str, template: str) -> str:
    base = (
        f"-- {name}/client.lua\n"
        f"-- Generated by Sanitize V scaffolder\n\n"
        f"local function notify(msg)\n"
        f"    SetNotificationTextEntry('STRING')\n"
        f"    AddTextComponentString(msg)\n"
        f"    DrawNotification(false, false)\n"
        f"end\n\n"
    )
    if template == "esx":
        base += (
            "ESX = nil\n"
            "Citizen.CreateThread(function()\n"
            "    while ESX == nil do\n"
            "        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)\n"
            "        Citizen.Wait(0)\n"
            "    end\n"
            "end)\n"
        )
    elif template == "qbcore":
        base += "local QBCore = exports['qb-core']:GetCoreObject()\n"

    base += (
        "\nRegisterNetEvent('" + name + ":sayHi')\n"
        "AddEventHandler('" + name + ":sayHi', function(msg)\n"
        "    notify('Hello from " + name + ": ' .. tostring(msg))\n"
        "end)\n"
    )
    return base


def _server_text(name: str, template: str) -> str:
    if template == "esx":
        return (
            f"-- {name}/server.lua\n"
            f"local ESX = exports['es_extended']:getSharedObject()\n\n"
            f"ESX.RegisterCommand('{name}', 'user', function(xPlayer, args)\n"
            f"    xPlayer.triggerEvent('{name}:sayHi', 'ESX command worked!')\n"
            f"end, false, {{help = 'Demo {name} command'}})\n"
        )
    if template == "qbcore":
        return (
            f"-- {name}/server.lua\n"
            f"local QBCore = exports['qb-core']:GetCoreObject()\n\n"
            f"QBCore.Commands.Add('{name}', 'Demo {name} command', {{}}, false, function(source, args)\n"
            f"    TriggerClientEvent('{name}:sayHi', source, 'QBCore command worked!')\n"
            f"end)\n"
        )
    return (
        f"-- {name}/server.lua\n\n"
        f"RegisterCommand('{name}', function(source, args, rawCommand)\n"
        f"    TriggerClientEvent('{name}:sayHi', source, table.concat(args, ' '))\n"
        f"end, false)\n"
    )


def _config_text(name: str) -> str:
    return (
        f"Config = Config or {{}}\n\n"
        f"-- Configuration for {name}\n"
        f"Config.Debug   = false\n"
        f"Config.Locale  = 'en'\n"
    )
